// Conteúdo compartilhado entre as variações — PT/EN
window.PORTFOLIO_DATA = {
  name: "Luiz Antônio PC Bezerra",
  email: "luizantoniopcb@gmail.com",
  photo: "assets/profile.jpg",
  socials: [
    { label: "GitHub", url: "https://github.com/bezerraluiz" },
    { label: "LinkedIn", url: "https://www.linkedin.com/in/bezerraluiz/" },
    { label: "Instagram", url: "https://www.instagram.com/bezerraluiz.dev/" },
  ],
  t: {
    pt: {
      hello: "Olá! Eu sou",
      role: "Desenvolvedor Full Stack",
      tagline: "Transformando ideias em código.",
      cta: "Me envie um email",
      nav: { about: "Sobre", projects: "Projetos" },
      aboutTitle: "Sobre mim",
      about1: "Tenho mais de 3 anos de experiência como Desenvolvedor.",
      about2: "Sempre olho para o problema, pensando na ideia que irá resolvê-lo.",
      about3: "Acredito que simplicidade é o segredo para soluções elegantes.",
      projectsTitle: "Meus projetos",
      code: "Código",
      live: "Ver projeto",
      available: "Disponível para novos projetos",
      footer: "Desenvolvido com React + Vite & Tailwind CSS",
    },
    en: {
      hello: "Hi! I'm",
      role: "Full Stack Developer",
      tagline: "Turning ideas into code.",
      cta: "Send me an email",
      nav: { about: "About", projects: "Projects" },
      aboutTitle: "About me",
      about1: "I have 3+ years of experience as a Developer.",
      about2: "I always start from the problem, thinking about the idea that will solve it.",
      about3: "I believe simplicity is the secret to elegant solutions.",
      projectsTitle: "My projects",
      code: "Code",
      live: "Live site",
      available: "Available for new projects",
      footer: "Built with React + Vite & Tailwind CSS",
    },
  },
  projects: [
    {
      title: "Loom — AI Project Management",
      desc: {
        pt: "Control plane open-source e 100% local para orquestrar agentes de IA de código (Claude Code, Gemini CLI, Codex e mais). Vue 3 + Spring Boot.",
        en: "Open-source, 100% local control plane to orchestrate AI coding agents (Claude Code, Gemini CLI, Codex and more). Vue 3 + Spring Boot.",
      },
      tags: ["Vue 3", "Spring Boot", "Vite", "SQLite"],
      codeUrl: "https://github.com/luizantoniopcbezerra/loom-ai",
      liveUrl: "https://luizantoniopcbezerra.github.io/loom-lp/",
      image: "src/assets/img-projects/loom.png",
    },
    {
      title: "MCP Master of Puppets",
      desc: {
        pt: "Servidor MCP para comunicação assíncrona entre agentes de IA, com caixas de entrada baseadas em arquivos versionados no git.",
        en: "MCP server for async communication between AI agents, using git-tracked file-based inboxes.",
      },
      tags: ["Python", "MCP", "YAML"],
      codeUrl: "https://github.com/luizantoniopcbezerra/mcp-master-of-puppets",
      liveUrl: null,
      image: null,
    },
    {
      title: "APA São Ludgero",
      desc: {
        pt: "Sistema web para a ONG APA São Ludgero, com cadastro de animais, adoção e doações.",
        en: "Web system for the APA São Ludgero NGO, with animal registration, adoption and donations.",
      },
      tags: ["React.js", "Java", "PostgreSQL", "Spring"],
      codeUrl: "https://github.com/arturoburigo/Adopet",
      liveUrl: null,
      image: "src/assets/img-projects/adopet.png",
    },
    {
      title: "A Cura D'Alma e Cigano Vladimir",
      desc: {
        pt: "Landing page para taróloga com consultas presenciais e à distância — serviços, valores e redes sociais.",
        en: "Landing page for a tarot reader offering in-person and remote sessions — services, pricing and socials.",
      },
      tags: ["HTML", "CSS", "JavaScript"],
      codeUrl: "https://github.com/bezerraluiz/curadalma-ciganovladimir",
      liveUrl: "https://curadalmaciganovladimir.com/",
      image: "src/assets/img-projects/curadalmaciganovladimir.jpg",
    },
    {
      title: "Doski Gi Tattoo Portfolio",
      desc: {
        pt: "Portfólio para a tatuadora Doski Gi, com trabalhos realizados, contato e redes sociais.",
        en: "Portfolio for tattoo artist Doski Gi, showcasing her work, contact info and socials.",
      },
      tags: ["HTML", "CSS", "JavaScript"],
      codeUrl: "https://github.com/bezerraluiz/doski.gi-portfolio",
      liveUrl: "https://doskigitattoo.netlify.app/",
      image: "src/assets/img-projects/doskigiportfolio.jpg",
    },
    {
      title: "HBL Ofertas — Frontend",
      desc: {
        pt: "Sistema web de ofertas, com cadastro de produtos e gerenciamento de ofertas.",
        en: "Deals web system with product registration and offer management.",
      },
      tags: ["React.js", "Next.js", "JavaScript", "CSS"],
      codeUrl: "https://github.com/bezerraluiz/hbl-ofertas-frontend",
      liveUrl: "https://hblofertas.com.br/",
      image: "src/assets/img-projects/hblofertas.jpg",
    },
    {
      title: "HBL Ofertas — Backend",
      desc: {
        pt: "CRUD completo do sistema, com integração ao Google Drive para salvar imagens.",
        en: "Full CRUD backend with Google Drive integration for image storage.",
      },
      tags: ["Node.js", "Fastify", "TypeScript", "PostgreSQL"],
      codeUrl: "https://github.com/bezerraluiz/hbl-ofertas-backend",
      liveUrl: null,
      image: "src/assets/img-projects/diagram.png",
    },
  ],
};
